### ISSUE TITLE
prop "key" is handled incorrectly

### ISSUE THREAD

**Issue by jrieks** [akryl-kt/akryl-core#1]
This code:

```
fun number(key: String, i: Int) = component {
	html("li", innerHtml = "i:$i key:$key")
}
fun loop() = component {
	html("ol",
		children = listOf(1,2,3).map {
			number(it.toString(), it)
		}
	)
}
```

is rendered like this:
![image](https://user-images.githubusercontent.com/3511612/79799446-c1cdb280-835a-11ea-99d9-71c650312563.png)

if the key is unused like here:
```
fun number(key: String, i: Int) = component {
	html("li", innerHtml = "i:$i")
}
```
it is rendered this way (e.g. there is no "key" anymore in the react components tree):
![image](https://user-images.githubusercontent.com/3511612/79799691-2db01b00-835b-11ea-83c5-15fa5fb292c4.png)

How is "key" supposed to be used? Shouldn't it be possible to declare the key inside a component, maybe like this?
```
fun number(i: Int) = component {
	html("li", attributes = mapOf("key" to "$i"), innerHtml = "i:$i")
}
```

**Comment by ashlanderr** [comment]
The "key" is a special property in React. You cannot use it to pass data to components. There is a function [withKey](https://github.com/akryl-kt/akryl-core/blob/18c5a4be30ef97f6b2611a79baaeb39bab94536b/src/main/kotlin/io/akryl/Component.kt#L88), that can be used to pass "key" as an identity mark for elements in the loop. 

Also, you can use functions like `Li`, or `Div` to create DOM elements. `html` is a low-level function.

```kotlin
fun number(i: Int) = component {
    Li(text = "i:$i")
}

fun loop() = component {
    Ol(
        children = listOf(1, 2, 3).map { 
            number(it).withKey(it) 
        }
    )
}
```

I don't know how to pass the "key" in a more convenient way, considering how props are passed to a component.

**Comment by jrieks** [comment]
Thank you for your clarification, I was not aware of the withKey method...
